# Resumen {.unnumbered}

Esta tesis presenta el desarrollo de LegionGOES como un sistema de software orientado a la descarga, procesamiento, organización, visualización y generación de productos derivados a partir de información satelital geoestacionaria de la serie GOES-R. El trabajo se centra en la construcción de una herramienta computacional reproducible, instalable y utilizable en entornos locales de Windows, capaz de integrar rutinas de procesamiento, interfaces gráficas, manejo de archivos `NetCDF`, generación de imágenes, producción de videos y exploración de series temporales. El diseño de una arquitectura de software tiene una fuerte impronta en convertir datos complejos en salidas visuales interpretables y operativamente accesibles.

LegionGOES combina componentes desarrollados en Python, R/Shiny y recursos locales dentro de un entorno distribuido mediante instalador. Esta decisión responde a un problema frecuente en el uso científico y técnico de herramientas computacionales que es la dificultad de reproducir procesos cuando dependen de configuraciones particulares del sistema operativo, versiones de bibliotecas, rutas de archivos, dependencias externas o conocimientos avanzados de programación. En este sentido, el software busca reducir la distancia entre el dato satelital original y el usuario final mediante flujos de trabajo estructurados, interfaces específicas por temáticas meteorológicas y una organización interna que separa herramientas de respuesta rápida de herramientas de análisis acumulativo.

Dentro del conjunto de temáticas meteorológicas posibles de analizar con la serie GOES-R, esta tesis aborda la temperatura de superficie, los focos de calor, las nubes y la actividad eléctrica. Se trata de temáticas ampliamente estudiadas a escala regional, nacional e internacional, cuya sistematización dentro de un mismo entorno de trabajo puede favorecer la estandarización de procedimientos y generar un impacto significativo en el área y en los profesionales que utilizan información satelital. En LegionGOES, estas temáticas son resueltas mediante productos GOES específicos: `ABI-L2-LSTF`, `ABI-L2-FDCF`, `ABI-L2-MCMIPF` y `GLM-L2-LCFA`. A partir de ellos, la tesis evalúa decisiones de diseño, procesamiento y visualización dentro del software. La tesis discute el estado del arte de herramientas como SLIDER, QGIS y Jupyter Notebook, analiza la evolución del proyecto desde una idea inicial basada en servidor hacia un software instalable, describe las limitaciones actuales del sistema y plantea líneas de proyección futura. En conjunto, LegionGOES se propone como una contribución tecnológica para facilitar el uso local, reproducible y visualmente comunicable de productos GOES en contextos donde este tipo de información satelital es requerida.

**Palabras clave:** LegionGOES; software científico; GOES; R/Shiny; Python; reproducibilidad computacional; visualización satelital; series temporales.

```{=latex}
\clearpage
```
