# Conclusiones

Los objetivos planteados para la tesis han sido cumplidos: fue generado un software de acceso libre para el procesamiento de imágenes GOES con fines agrometeorológicos  que peprmite la viusalización de series de tiempo. Al momento de escribir esta tesis ha sido probado de manera exitosa por 20 personas.

A nivel institucional, desde el Centro de Altos Estudios Espaciales Mario Gulich, LegionGOES es el primer software GIS de distribución libre generado en todas sus cohortes.

Argentina es un referente internacional en temas espaciales. LegionGOES logra un aporte más en esa historia en el área de desarrollo de softwarae para análisis de imágenes satelitales. 


Las temáticas agrometeorológicas no son nuevas, de hecho son ancestrales como fue detallado al inicio de la tesis.
Tampoco hay una novedad sobre el código de procesamiento propiamente ya que hay muchísimo código Python que ha sido utilizado profesionales y tesistas en los últimso años. Siempre habrá dificultades para armar el código de procesamiento pero no es algo que no se haya visto anteriormente.

El aporte de LegionGOES que son las prestaciones o características que no se encuentran en otros softwares:  
- La generación de interfaz web en entorno local amena e intuitiva.  
- La maximización del espacio visual dedicado efectivamente a los productos satelitales y reportería.  
- La generación de series temporales dentro de un software de escritorio.  
- La utilización de Python y R de manera simultánea en una sola unidad de procesamiento y visualización.  
- La posibilidad dentro de un software GIS de obtener de manera automática un reporte pdf, un reporte html, una carpeta zip con todos los png de cada frame, y un video mp4 de la serie temporal. LegionGOES es el primero en ofrecer esas posibilidades.  





